### ISSUE TITLE
Function Calling (tools) implementation

### ISSUE THREAD

**Issue by lucianosrp** [kennethreitz/simplemind#40]
Are tools/function calling planned to be implemented as part of this API?
I think this is a major bit that is still missing.

I could give it a go if no one is working on it 👍

**Comment by kennethreitz** [comment]
Yes, would love to see a proposal for this!

**Comment by Red5d** [comment]
Based on my understanding of how tool/function calling works, I'm currently doing that with a plugin that intercepts the request, checks if a tool should be used, executes it if so, and returns the results back to the conversation for processing. Would this feature be better implemented as an included or example plugin rather than part of the API? 
![image](https://github.com/user-attachments/assets/0e609b02-af0a-4ac7-945f-ace5f45a00d9)

**Comment by kennethreitz** [comment]
perhaps we need the ability to stream responses from a conversation
